//gitlab的凭证
def tag = "latest"
def git_auth = "b280ac3c-a887-41eb-83f8-1cb1c13cbc93"
node {
    stage('拉取代码') {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    userRemoteConfigs: [[credentialsId: "${git_auth}",
                    url: 'git@github.com:Innocent-He/pna-web.git']]
        ])
    }
    stage('编译，构建镜像') {
        //编译，构建本地镜像
        sh "mvn -f pna-web  clean package"
        sh "sh ./pna-web/pna-start.sh"
    }
    stage('打包，部署前端'){
        nodejs('nodejs16'){
            sh '''
                cd ./pna-vue
                npm install
                npm run build
                mv -fu ./dist/* /usr/local/html/pna
            '''
        }

    }
}
