spring:
  datasource:
    url: jdbc:mysql://82.157.55.18:3306/pna?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Gy612200.
  redis:
    # Redis服务器地址
    host: 82.157.55.18
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: hegaoyun
